
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      CRM:
        automatic-transition-from-open-to-half-open-enabled: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        sliding-window-size: 5
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 5s
