spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: CRMAPP
          uri: lb://CRMAPP
          predicates:
            - Path=/user/**
           
        - id: CRMAPP
          uri: lb://CRMAPP
          predicates:
            - Path=/leads/**
        - id: CRMAPP
          uri: lb://CRMAPP
          predicates:
            - Path=/opportunity/**     
        - id: CRMADMIN
          uri: lb://CRMADMIN
          predicates:
            - Path=/admin/**
        